apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-showcase-gitops
  namespace: argocd
  # Finalizer enables cascading deletes when application is removed
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  # Source definition pointing to the GitOps manifests repository
  source:
    # REPLACE 'yourgithubusername/gitops-manifests-repo' with your own GitHub manifests repository (e.g. 'omarwaziry/enterprise-gitops-manifests')
    repoURL: 'https://github.com/yourgithubusername/gitops-manifests-repo.git'
    targetRevision: HEAD
    path: . # Synchronize manifests in the root of the repository
  
  # Destination details pointing to local target cluster
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production

  # Sync policy configuration
  syncPolicy:
    automated:
      prune: true      # Automatically delete resources no longer present in Git
      selfHeal: true   # Reconcile manual out-of-sync cluster changes automatically
    syncOptions:
      - CreateNamespace=true # Create target namespace if not exists
      - ApplyOutOfSyncOnly=true
